### ISSUE TITLE
Windows runtime: process.binding('contextify') Error: No such module

### ISSUE THREAD

**Issue by nhandl3** [electron/node#4] opened 2014-09-23 05:24 UTC
I tried to build this embedded node with vcbuild nosign
All build ok, node --version shows v0.11.13
But when run node alone or with js file it returns follow error:

```
d:\toollib\atom-editor\atom-shell\vendor\node\Release>node server.js
node.js:738
  var ContextifyScript = process.binding('contextify').ContextifyScript;
                                 ^
Error: No such module
    at Error (native)
    at node.js:738:34

d:\toollib\atom-editor\atom-shell\vendor\node\Release>
```

I have google but seem no clear clues.
Still investigating...

**Comment by zombiezen** [comment] 2015-04-19 19:39
For others who have hit this issue while trying to build Node.js in non-standard ways, the problem is that all of Node.js's built-in modules are initialized using the `__attribute__((constructor))` (on Unix) or `dllexport` (on Windows).  If you're building statically, these get stripped.

The workaround that I used was to modify the `NODE_C_CTOR` macro to have external linkage and call the module constructors from main.  It's a pain, but it gets things moving.

**Comment by irbull** [comment] 2016-06-24 03:22
@zombiezen Do you have a link to what you changed? I'm up against this exact issue. Thanks so much!

**Comment by zombiezen** [comment] 2016-07-02 15:48
I don't have a link, but it's a rather straightforward change:

```c
// node.h
#define NODE_C_CTOR(fn) void fn(void)

// node_main.cc
extern "C" {
  void _register_async_wrap(void);
  // etc...
}

int main(int argc, char *argv[]) {
  _register_async_wrap();
  // etc...
}
```

**Comment by irbull** [comment] 2016-07-20 16:36
@zombiezen Thank-you so much. I was trying to call the `Initialize` method on each modules, which often has different syntax for each module. You're solution was exactly what I needed and I doubt I would have figured that out without you. https://github.com/eclipsesource/J2V8/commit/5dd9c0a7581ba1550c3ccebced9b8e35a70518c2

If I ever meet you, a drink is certainly on me.

Thanks again!

**Comment by tommyZZM** [comment] 2017-10-06 12:40
for others who wants to embed node as static library have hit this issue, 
could also see this issue: https://github.com/janeasystems/nodejs-mobile/issues/9

**Comment by MarshallOfSound** [comment] 2018-09-28 01:36
This issue is very old and does not directly pertain to any issue with electron's embedding of node, gonna close it out 👍

**Closed by MarshallOfSound** 2018-09-28 01:36 UTC
